services:
  db:
    image: mysql
    restart: unless-stopped
    env_file:
      - .env 
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db-backup:/db-backup
    networks:
      - backend
    hostname: db

  api:
    build: ./api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_PORT
    networks:
      - backend
      - frontend
    depends_on:
      - db

  app:
    build: ./app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $APP_LOCAL_PORT:$APP_DOCKER_PORT
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/index.html:/app/index.html
    networks:
      - frontend
    depends_on:
      - db
      - api
    command: npm run dev

volumes:
  db:

networks:
  backend:
  frontend: